prometheus:
  image: prom/prometheus:v2.37.0
  container_name: clube-do-java-prometheus
  restart: always
  volumes:
    - ./prometheus:/etc/prometheus
    - prometheus-data:/prometheus
  networks:
    - clube-java-network
  command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/usr/share/prometheus/console_libraries'
    - '--web.console.templates=/usr/share/prometheus/consoles'
  depends_on:
    - app

  # Grafana para visualização de métricas (opcional)
  grafana:
    image: grafana/grafana:9.0.0
    container_name: clube-do-java-grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - clube-java-network
    depends_on:
      - prometheus

networks:
  clube-java-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  prometheus-data:
  grafana-data: